//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a folder for output.
        /// </summary>
        internal static string PrintGif_btnGo_Click_Please_Select_a_folder_for_output {
            get {
                return ResourceManager.GetString("PrintGif_btnGo_Click_Please_Select_a_folder_for_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a GIF file for conversion.
        /// </summary>
        internal static string PrintGif_btnGo_Click_Please_Select_a_GIF_file_for_conversion {
            get {
                return ResourceManager.GetString("PrintGif_btnGo_Click_Please_Select_a_GIF_file_for_conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Files (*.gif)|*.gif.
        /// </summary>
        internal static string PrintGif_btnSelectGif_Click_GIF_Files____gif____gif {
            get {
                return ResourceManager.GetString("PrintGif_btnSelectGif_Click_GIF_Files____gif____gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a GIF file to be converted..
        /// </summary>
        internal static string PrintGif_btnSelectGif_Click_Please_select_a_GIF_file_to_be_converted_ {
            get {
                return ResourceManager.GetString("PrintGif_btnSelectGif_Click_Please_select_a_GIF_file_to_be_converted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went tits up!.
        /// </summary>
        internal static string PrintGif_PreviewMontage_Something_went_tits_up_ {
            get {
                return ResourceManager.GetString("PrintGif_PreviewMontage_Something_went_tits_up_", resourceCulture);
            }
        }
    }
}
